In [7]:
import sklearn.datasets
import numpy as np
import random
import pandas as pd
#X = data["data"]
#y = data["target"]
from numpy import mean
from numpy import std
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import xgboost as xgb
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib as plt

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.naive_bayes import GaussianNB
from time import process_time
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFE
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict, KFold

In [3]:
data = pd.read_csv("#dataset_path")
#data.drop("Id", axis=1, inplace=True)
data = data.iloc[:,7:]
data

position_id  attribute_value_ml_acceleration  \
0               2                        42.505460   
1              10                        42.505460   
2               5                        55.412505   
3               3                        70.506566   
4               7                        70.506566   
...           ...                              ...   
1008            6                        44.105567   
1009            8                        68.596128   
1010            2                        44.105567   
1011           10                        51.503158   
1012            5                        51.503158   

      attribute_value_ml_aerial_ability  attribute_value_ml_agility  \
0                             30.394741                   42.505460   
1                             55.412505                   42.505460   
2                             42.505460                   55.412505   
3                             42.505460                   55.412505   
4                             42.505460                   70.506566   
...                                 ...                         ...   
1008                          29.090506                   51.503158   
1009                          46.956626                   51.503158   
1010                          44.105567                   36.766581   
1011                          51.503158                   51.503158   
1012                          20.192805                   51.503158   

      attribute_value_ml_anticipation  attribute_value_ml_balance  \
0                           30.394741                   42.505460   
1                           42.505460                   55.412505   
2                           55.412505                   55.412505   
3                           42.505460                   55.412505   
4                           55.412505                   55.412505   
...                               ...                         ...   
1008                        36.766581                   36.766581   
1009                        50.422883                   51.503158   
1010                        44.105567                   44.105567   
1011                        44.105567                   51.503158   
1012                        51.503158                   29.090506   

      attribute_value_ml_bravery  attribute_value_ml_command_of_area  \
0                      30.394741                           50.650274   
1                      42.505460                           50.650274   
2                      55.412505                           50.650274   
3                      42.505460                           50.650274   
4                      55.412505                           50.650274   
...                          ...                                 ...   
1008                   52.431914                           50.650274   
1009                   52.431914                           50.650274   
1010                   52.431914                           50.650274   
1011                   52.431914                           50.650274   
1012                   52.431914                           50.650274   

      attribute_value_ml_communication  attribute_value_ml_composure  ...  \
0                            30.394741                     30.394741  ...   
1                            42.505460                     42.505460  ...   
2                            55.412505                     55.412505  ...   
3                            30.394741                     42.505460  ...   
4                            55.412505                     55.412505  ...   
...                                ...                           ...  ...   
1008                         36.766581                     29.090506  ...   
1009                         51.657430                     50.947070  ...   
1010                         51.657430                     44.105567  ...   
1011                         51.657430  

In [19]:
corr = data['position_id'].corr(data['Label_Category_Num'])
corr


0.244607231209382

In [ ]:
df_x = data.iloc[:,:-1]
df_y = data.iloc[:,[-1]]

In [ ]:
t1_start = process_time() 
sel = RFE(RandomForestClassifier(n_estimators = 10, random_state = 10), n_features_to_select = 10)
sel.fit(df_x, df_y)
t1_stop = process_time()
print("time:", t1_stop-t1_start)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:283: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X[:, features], y, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:283: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X[:, features], y, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:283: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X[:, features], y, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:283: DataConversionWarning: A column-vector y was passed when a 1d array was expe

time: 1.2372213970000008


/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:283: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X[:, features], y, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_rfe.py:310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X[:, features], y, **fit_params)


In [ ]:
selected_feat= df_x.columns[(sel.get_support())]
len(selected_feat)

10

In [ ]:
print(selected_feat)

Index(['attribute_value_ml_acceleration', 'attribute_value_ml_creativity',
       'attribute_value_ml_crossing', 'attribute_value_ml_dribling',
       'attribute_value_ml_finishing', 'attribute_value_ml_flair',
       'attribute_value_ml_marking', 'attribute_value_ml_passing',
       'attribute_value_ml_team_work', 'attribute_value_ml_technique'],
      dtype='object')


In [ ]:
df_x2 = df_x[selected_feat]

In [ ]:
res_df = pd.concat([df_x2, df_y], axis = 1)

In [ ]:
res_x = res_df.iloc[:,:-1]
res_y = res_df.iloc[:,[-1]]

In [ ]:
model = RandomForestClassifier()

In [ ]:
t1_start = process_time() 
kfold = KFold(n_splits = 10, random_state = 1, shuffle = True)
results = cross_val_score(model, res_x, res_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(model, res_x , res_y,cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, res_y))
print("Confusion Metrix : \n", confusion_matrix(predict, res_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 

Accuracy :  0.8864201125994953
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.91      0.94       970
           1       0.21      0.56      0.30        43

    accuracy                           0.89      1013
   macro avg       0.59      0.73      0.62      1013
weighted avg       0.95      0.89      0.91      1013

Confusion Metrix : 
 [[879  91]
 [ 19  24]]
time: 5.553589944000002


In [ ]:
model = DecisionTreeClassifier()
t1_start = process_time() 
kfold = KFold(n_splits = 10, random_state = 1, shuffle = True)
results = cross_val_score(model, res_x, res_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(model, res_x , res_y,cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, res_y))
print("Confusion Metrix : \n", confusion_matrix(predict, res_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

Accuracy :  0.8291982139390409
Classification Report : 
               precision    recall  f1-score   support

           0       0.89      0.91      0.90       871
           1       0.35      0.28      0.31       142

    accuracy                           0.83      1013
   macro avg       0.62      0.60      0.61      1013
weighted avg       0.81      0.83      0.82      1013

Confusion Metrix : 
 [[796  75]
 [102  40]]
time: 0.24838311199999907


In [ ]:
model = GaussianNB()
t1_start = process_time() 
kfold = KFold(n_splits = 10, random_state = 1, shuffle = True)
results = cross_val_score(model, res_x, res_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(model, res_x , res_y,cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, res_y))
print("Confusion Metrix : \n", confusion_matrix(predict, res_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

Accuracy :  0.8271986022131624
Classification Report : 
               precision    recall  f1-score   support

           0       0.86      0.94      0.90       824
           1       0.57      0.35      0.43       189

    accuracy                           0.83      1013
   macro avg       0.72      0.64      0.67      1013
weighted avg       0.81      0.83      0.81      1013

Confusion Metrix : 
 [[775  49]
 [123  66]]
time: 0.12447931999999895


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
model = LogisticRegression()
t1_start = process_time() 
kfold = KFold(n_splits = 10, random_state = 1, shuffle = True)
results = cross_val_score(model, res_x, res_y, scoring = 'accuracy', cv = kfold)
predict = cross_val_predict(model, res_x , res_y,cv = 10)
print("Accuracy : ", results.mean())
print("Classification Report : \n", classification_report(predict, res_y))
print("Confusion Metrix : \n", confusion_matrix(predict, res_y))
t1_stop = process_time()
print("time:", t1_stop-t1_start)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example

Accuracy :  0.8913511939429238
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.91      0.94       972
           1       0.22      0.61      0.32        41

    accuracy                           0.90      1013
   macro avg       0.60      0.76      0.63      1013
weighted avg       0.95      0.90      0.92      1013

Confusion Metrix : 
 [[882  90]
 [ 16  25]]
time: 0.6881894089999996


In [ ]:

xgb_cls = xgb.XGBClassifier(objective="multi:softmax", num_class=2)

In [ ]:
xgb_cls.fit(X_train, y_train)

XGBClassifier(num_class=2, objective='multi:softmax')

In [ ]:
preds = xgb_cls.predict(X_test)

In [ ]:
accuracy_score(y_test, preds)

0.8768472906403941